/*UserData*/
var ISLOGIN = "ISLOGIN";
var TOKEN = "TOKEN";
var USER_NAME = "USER_NAME";
var USER_MOBILE = "USER_MOBILE";
var USER_ID = "USER_ID";
var DEVICE_ID = "DEVICE_ID";
var SELECTED_ADDRESS_ID = "SELECTED_ADDRESS_ID";
var SELECTED_ADDDRESS = "SELECTED_ADDDRESS";
var SELECTED_ADDDRESS_TYPE = "SELECTED_ADDDRESS_TYPE";
var SELECTED_LATITUDE = "SELECTED_LATITUDE";
var SELECTED_LONGITUDE = "SELECTED_LONGITUDE";
var TERMS_CONDITION = "TERMS_CONDITION";
var PRIVACY_POLICY = "RPIVACY_POLICY";
var MOBILE_CONTACT = "MOBILE_CONTACT";
var EMAIL_CONTACT = "EMAIL_CONTACT";
var WHATSAPP_CONTACT = "WHATSAPP_CONTACT";
